version: 0.2
env:
  secrets-manager:
    DOCKER_HUB_USERNAME: "dockerhub:username"
    DOCKER_HUB_PASSWORD: "dockerhub:password"
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  build:
    commands:
      - echo Build started on `date`.
      - echo Beginning tests.
      - mvn verify
      - echo tests complete.
      # We're not currently, running the WS on ECR so just build the docker image and later push it to a registry
      - echo Docker Build started on `date`.
      - docker build -t tobypeel/steam_group_game_checker_api:prod .
      - echo Build completed on `date`.
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push tobypeel/steam_group_game_checker_api:prod
reports:
  SggcWsUnitTestReport:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
  SggcWsIntegrationTestReport:
    files:
      - '**/*IT.xml'
      - '**/*Tests.xml'
    base-directory: 'target/failsafe-reports'
artifacts:
  files:
    - target/sggcws-2.0.0.jar
    - appspec.yml
  discard-paths: yes