version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - mvn surefire-report:report
      # We're not currently, running the WS on ECR so build the docker image and later push it to a registry
      - echo Docker Build started on `date`
      - docker build -t tobypeel/steam_group_game_checker_api:latest .
      - docker tag tobypeel/steam_group_game_checker_api:latest tobypeel/steam_group_game_checker_api:prod
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - echo Pushing the Docker images...
      - docker push tobypeel/steam_group_game_checker_api:latest
      - docker push tobypeel/steam_group_game_checker_api:prod
reports:
  SggcWsUniTestReport:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
artifacts:
  files:
    - target/sggcws-1.1.1.jar
    - appspec.yml
  discard-paths: yes