package com.sggc.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.math.BigInteger;

@Data
@RequiredArgsConstructor
@DynamoDBTable(tableName = "Game")
public class Game {
    @JsonIgnore
    private BigInteger id;
    @JsonProperty("appid")
    private String appid;
    private String name;
    @JsonIgnore
    private Boolean multiplayer;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public BigInteger getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getAppid() {
        return appid;
    }
    @DynamoDBAttribute
    public String getName() {
        return name;
    }
    @DynamoDBAttribute
    public Boolean getMultiplayer() {
        return multiplayer;
    }
}

