package com.sggc.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

import javax.persistence.ElementCollection;
import java.util.Set;

@Data
@DynamoDBTable(tableName = "User")
@RequiredArgsConstructor
@NoArgsConstructor
public class User {
    @NonNull
    private String id;
    @ElementCollection
    @NonNull
    private Set<String> ownedGameIds;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public Set<String> getOwnedGameIds() {
        return ownedGameIds;
    }

    //TTL (time-to-live) field for DynamoDB
    @NonNull
    private double removalDate;
}
