version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    volumes:
      - ./init-scripts:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
