version: '3.8'
services:
  localstack-aws-secrets-manager:
    image: localstack/localstack:latest
    container_name: sggc-local-aws-secrets-manager
    ports:
      - "4566:4566"
    volumes:
      - ./AWS-Secrets-Manager/init-scripts:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock

  dynamodb-local:
    image: tobypeel/steam_group_game_checker_local_db:latest
    container_name: sggc-local-dynamodb
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: sggc-local-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "eu-west-2"
      AWS_ACCESS_KEY_ID: DUMMY_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: DUMMY_SECRET_ACCESS_KEY
    depends_on:
      - dynamodb-local

  steam-wiremock:
    image: wiremock/wiremock
    container_name: sggc-local-steam-api-mock
    ports:
      - "9000:8080"
